#from Layer.layer import *
from waff.Layers.convolutionLayer import Conv
#from waff.Layers.layer import Layer
from waff.Layers.deconvolutionLayer import Deconv
from waff.Layers.core import Dense
from waff.Layers.pool import AvgPool2d,MaxPool2d
from waff.Layers.activations import ReLU,Softmax,Sigmoid,Tanh
from waff.Layers.batchNorm import BatchNorm,GroupNorm
from waff.Layers.dropout import Dropout
from waff.Layers.concat import Concat
from waff.Layers.add import Add
from waff.Layers.flatten import Flatten
from waff.Layers.depthwise_conv import DepthwiseConv
from waff.Layers.pointwise_conv import PointwiseConv
